project.clj

prismatic/schema 0.3.4 has been released. Previous version was 0.3.3.

prismatic/schema 0.3.4 released

---

project.clj

prismatic/schema 0.3.5 has been released. Previous version was 0.3.4.

prismatic/schema 0.3.5 released

---

project.clj

prismatic/schema 0.3.6 has been released. Previous version was 0.3.5.

prismatic/schema 0.3.6 released

---

project.clj

prismatic/schema 0.3.7 has been released. Previous version was 0.3.6.

prismatic/schema 0.3.7 released

---

project.clj

lein-ancient 0.6.2 has been released. Previous version was 0.6.1.

lein-ancient 0.6.2 released

---

project.clj

org.clojure/core.typed 0.2.78 has been released. Previous version was 0.2.77.

org.clojure/core.typed 0.2.78 released

---

project.clj

ring/ring-defaults 0.1.4 has been released. Previous version was 0.1.3.

ring/ring-defaults 0.1.4 released

---

project.clj

aleph 0.4.0-beta3 has been released. Previous version was 0.4.0-beta2.

aleph 0.4.0-beta3 released

---

project.clj

com.taoensso/nippy 2.8.0 has been released. Previous version was 2.7.1.

com.taoensso/nippy 2.8.0 released

---

project.clj

org.clojure/core.typed 0.2.82 has been released. Previous version was 0.2.81.

org.clojure/core.typed 0.2.82 released

---

project.clj

org.clojure/core.typed 0.2.83 has been released. Previous version was 0.2.82.

org.clojure/core.typed 0.2.83 released

---

project.clj

lein-ancient 0.6.4 has been released. Previous version was 0.6.3.

lein-ancient 0.6.4 released

---

project.clj

prismatic/schema 0.4.0 has been released. Previous version was 0.3.7.

prismatic/schema 0.4.0 released

---

project.clj

lein-ancient 0.6.5 has been released. Previous version was 0.6.4.

lein-ancient 0.6.5 released

---

project.clj

org.clojure/core.typed 0.2.84 has been released. Previous version was 0.2.83.

org.clojure/core.typed 0.2.84 released

---

project.clj

ring-middleware-format 0.5.0 has been released. Previous version was 0.4.0.

ring-middleware-format 0.5.0 released

---

project.clj

org.clojure/clojure 1.7.0-alpha6 has been released. Previous version was 1.7.0-alpha5.

org.clojure/clojure 1.7.0-alpha6 released

---

project.clj

org.clojure/core.typed 0.2.85 has been released. Previous version was 0.2.84.

org.clojure/core.typed 0.2.85 released

---

project.clj

compojure 1.3.3 has been released. Previous version was 1.3.2.

compojure 1.3.3 released

---

project.clj

org.clojure/core.typed 0.2.86 has been released. Previous version was 0.2.85.

org.clojure/core.typed 0.2.86 released

---

project.clj

lein-ancient 0.6.6 has been released. Previous version was 0.6.5.

lein-ancient 0.6.6 released

---

project.clj

org.clojure/clojure 1.7.0-beta1 has been released. Previous version was 1.7.0-alpha6.

org.clojure/clojure 1.7.0-beta1 released

---

project.clj

org.clojure/core.typed 0.2.87 has been released. Previous version was 0.2.86.

org.clojure/core.typed 0.2.87 released

---

project.clj

com.taoensso/nippy 2.9.0-beta1 has been released. Previous version was 2.8.0.

com.taoensso/nippy 2.9.0-beta1 released

---

project.clj

aleph 0.4.0 has been released. Previous version was 0.4.0-beta3.

aleph 0.4.0 released

---

project.clj

lein-ancient 0.6.7 has been released. Previous version was 0.6.6.

lein-ancient 0.6.7 released

---

project.clj

com.taoensso/nippy 2.9.0-beta2 has been released. Previous version was 2.9.0-beta1.

com.taoensso/nippy 2.9.0-beta2 released

---

project.clj

lein-kibit 0.1.0 has been released. Previous version was 0.0.8.

lein-kibit 0.1.0 released

---

project.clj

prismatic/schema 0.4.1 has been released. Previous version was 0.4.0.

prismatic/schema 0.4.1 released

---

project.clj

org.clojure/clojure 1.7.0-beta2 has been released. Previous version was 1.7.0-beta1.

org.clojure/clojure 1.7.0-beta2 released

---

project.clj

com.taoensso/nippy 2.9.0-RC1 has been released. Previous version was 2.9.0-beta2.

com.taoensso/nippy 2.9.0-RC1 released

---

project.clj

prismatic/schema 0.4.2 has been released. Previous version was 0.4.1.

prismatic/schema 0.4.2 released

---

project.clj

com.taoensso/nippy 2.9.0-RC2 has been released. Previous version was 2.9.0-RC1.

com.taoensso/nippy 2.9.0-RC2 released

---

project.clj

compojure 1.3.4 has been released. Previous version was 1.3.3.

compojure 1.3.4 released

---

project.clj

org.clojure/clojure 1.7.0-beta3 has been released. Previous version was 1.7.0-beta2.

org.clojure/clojure 1.7.0-beta3 released

---

project.clj

org.clojure/core.typed 0.2.91 has been released. Previous version was 0.2.90.

org.clojure/core.typed 0.2.91 released

---

project.clj

org.clojure/core.typed 0.2.92 has been released. Previous version was 0.2.91.

org.clojure/core.typed 0.2.92 released

---

project.clj

org.clojure/clojure 1.7.0-RC1 has been released. Previous version was 1.7.0-beta3.

org.clojure/clojure 1.7.0-RC1 released

---

project.clj

prismatic/schema 0.4.3 has been released. Previous version was 0.4.2.

prismatic/schema 0.4.3 released

---

project.clj

com.taoensso/timbre 4.0.0-beta1 has been released. Previous version was 3.4.0.

com.taoensso/timbre 4.0.0-beta1 released

---

project.clj

com.taoensso/timbre 4.0.0-beta2 has been released. Previous version was 4.0.0-beta1.

com.taoensso/timbre 4.0.0-beta2 released

---

project.clj

org.clojure/core.typed 0.3.0-alpha1 has been released. Previous version was 0.2.92.

org.clojure/core.typed 0.3.0-alpha1 released

---

project.clj

com.taoensso/timbre 4.0.0-beta4 has been released. Previous version was 4.0.0-beta2.

com.taoensso/timbre 4.0.0-beta4 released

---

project.clj

org.clojure/core.typed 0.3.0-alpha2 has been released. Previous version was 0.3.0-alpha1.

org.clojure/core.typed 0.3.0-alpha2 released

---

project.clj

com.taoensso/nippy 2.9.0-RC3 has been released. Previous version was 2.9.0-RC2.

com.taoensso/nippy 2.9.0-RC3 released

---

project.clj

org.clojure/core.typed 0.3.0-alpha3 has been released. Previous version was 0.3.0-alpha2.

org.clojure/core.typed 0.3.0-alpha3 released

---

project.clj

org.clojure/core.typed 0.3.0-alpha4 has been released. Previous version was 0.3.0-alpha3.

org.clojure/core.typed 0.3.0-alpha4 released

---

project.clj

com.taoensso/nippy 2.9.0 has been released. Previous version was 2.9.0-RC3.

com.taoensso/nippy 2.9.0 released

---

project.clj

com.taoensso/nippy 2.10.0-alpha2 has been released. Previous version was 2.9.0.

com.taoensso/nippy 2.10.0-alpha2 released

---

project.clj

org.clojure/core.typed 0.3.0-alpha5 has been released. Previous version was 0.3.0-alpha4.

org.clojure/core.typed 0.3.0-alpha5 released

---

project.clj

org.clojure/test.check 0.8.0-alpha2 has been released. Previous version was 0.8.0-ALPHA.

org.clojure/test.check 0.8.0-alpha2 released

---

project.clj

org.clojure/test.check 0.8.0-alpha3 has been released. Previous version was 0.8.0-alpha2.

org.clojure/test.check 0.8.0-alpha3 released

---

project.clj

com.taoensso/timbre 4.0.0-RC1 has been released. Previous version was 4.0.0-beta4.

com.taoensso/timbre 4.0.0-RC1 released

---

project.clj

com.taoensso/timbre 4.0.0 has been released. Previous version was 4.0.0-RC1.

com.taoensso/timbre 4.0.0 released

---

project.clj

com.taoensso/timbre 4.0.1 has been released. Previous version was 4.0.0.

com.taoensso/timbre 4.0.1 released

---

project.clj

aleph 0.4.1-alpha1 has been released. Previous version was 0.4.0.

aleph 0.4.1-alpha1 released

---

project.clj

org.clojure/core.typed 0.3.0 has been released. Previous version was 0.3.0-alpha5.

org.clojure/core.typed 0.3.0 released

---

project.clj

org.clojure/core.typed 0.3.1 has been released. Previous version was 0.3.0.

org.clojure/core.typed 0.3.1 released

---

project.clj

org.clojure/core.typed 0.3.2 has been released. Previous version was 0.3.1.

org.clojure/core.typed 0.3.2 released

---

project.clj

com.taoensso/timbre 4.0.2 has been released. Previous version was 4.0.1.

com.taoensso/timbre 4.0.2 released

---

project.clj

com.taoensso/nippy 2.10.0-alpha3 has been released. Previous version was 2.10.0-alpha2.

com.taoensso/nippy 2.10.0-alpha3 released

---

project.clj

org.clojure/core.typed 0.3.3 has been released. Previous version was 0.3.2.

org.clojure/core.typed 0.3.3 released

---

project.clj

org.clojure/clojure 1.7.0 has been released. Previous version was 1.7.0-RC1.

org.clojure/clojure 1.7.0 released

---

project.clj

org.clojure/core.typed 0.3.5 has been released. Previous version was 0.3.4.

org.clojure/core.typed 0.3.5 released

---

project.clj

lein-cljfmt 0.1.11 has been released. Previous version was 0.1.10.

lein-cljfmt 0.1.11 released

---

project.clj

org.clojure/core.typed 0.3.6 has been released. Previous version was 0.3.5.

org.clojure/core.typed 0.3.6 released

---

project.clj

lein-cljfmt 0.1.12 has been released. Previous version was 0.1.11.

lein-cljfmt 0.1.12 released

---

project.clj

lein-cljfmt 0.2.0 has been released. Previous version was 0.1.12.

lein-cljfmt 0.2.0 released

---

project.clj

com.taoensso/timbre 4.1.0-alpha1 has been released. Previous version was 4.0.2.

com.taoensso/timbre 4.1.0-alpha1 released

---

project.clj

org.clojure/core.typed 0.3.7 has been released. Previous version was 0.3.6.

org.clojure/core.typed 0.3.7 released

---

project.clj

compojure 1.4.0 has been released. Previous version was 1.3.4.

compojure 1.4.0 released

---

project.clj

lein-cljfmt 0.2.1 has been released. Previous version was 0.2.0.

lein-cljfmt 0.2.1 released

---

project.clj

aleph 0.4.1-alpha2 has been released. Previous version was 0.4.1-alpha1.

aleph 0.4.1-alpha2 released

---

project.clj

com.taoensso/timbre 4.1.0-alpha2 has been released. Previous version was 4.1.0-alpha1.

com.taoensso/timbre 4.1.0-alpha2 released

---

project.clj

org.clojure/clojure 1.8.0-alpha1 has been released. Previous version was 1.7.0.

org.clojure/clojure 1.8.0-alpha1 released

---

project.clj

org.clojure/core.typed 0.3.8 has been released. Previous version was 0.3.7.

org.clojure/core.typed 0.3.8 released

---

project.clj

org.clojure/clojure 1.8.0-alpha2 has been released. Previous version was 1.8.0-alpha1.

org.clojure/clojure 1.8.0-alpha2 released

---

project.clj

org.clojure/core.typed 0.3.9 has been released. Previous version was 0.3.8.

org.clojure/core.typed 0.3.9 released

---

project.clj

org.clojure/test.check 0.8.0-RC1 has been released. Previous version was 0.8.0-alpha3.

org.clojure/test.check 0.8.0-RC1 released

---

project.clj

org.clojure/clojure 1.8.0-alpha3 has been released. Previous version was 1.8.0-alpha2.

org.clojure/clojure 1.8.0-alpha3 released

---

project.clj

org.clojure/core.typed 0.3.10 has been released. Previous version was 0.3.9.

org.clojure/core.typed 0.3.10 released

---

project.clj

org.clojure/clojure 1.8.0-alpha4 has been released. Previous version was 1.8.0-alpha3.

org.clojure/clojure 1.8.0-alpha4 released

---

project.clj

com.taoensso/timbre 4.1.0 has been released. Previous version was 4.1.0-alpha2.

com.taoensso/timbre 4.1.0 released

---

project.clj

com.taoensso/nippy 2.10.0-alpha4 has been released. Previous version was 2.10.0-alpha3.

com.taoensso/nippy 2.10.0-alpha4 released

---

project.clj

org.clojure/test.check 0.8.0-RC3 has been released. Previous version was 0.8.0-RC2.

org.clojure/test.check 0.8.0-RC3 released

---

project.clj

lein-cljfmt 0.3.0 has been released. Previous version was 0.2.1.

lein-cljfmt 0.3.0 released

---

project.clj

org.clojure/core.typed 0.3.11 has been released. Previous version was 0.3.10.

org.clojure/core.typed 0.3.11 released

---

project.clj

com.taoensso/timbre 4.1.1 has been released. Previous version was 4.1.0.

com.taoensso/timbre 4.1.1 released

---

project.clj

prismatic/schema 0.4.4 has been released. Previous version was 0.4.3.

prismatic/schema 0.4.4 released

---

project.clj

prismatic/schema 1.0.0 has been released. Previous version was 1.0.0-alpha1.

prismatic/schema 1.0.0 released

---

project.clj

prismatic/schema 1.0.1 has been released. Previous version was 1.0.0.

prismatic/schema 1.0.1 released

---

project.clj

ring-middleware-format 0.6.0 has been released. Previous version was 0.5.0.

ring-middleware-format 0.6.0 released

---

project.clj

ring/ring-mock 0.3.0 has been released. Previous version was 0.2.0.

ring/ring-mock 0.3.0 released

---

project.clj

org.clojure/test.check 0.8.2 has been released. Previous version was 0.8.1.

org.clojure/test.check 0.8.2 released

---

project.clj

com.taoensso/nippy 2.10.0-alpha5 has been released. Previous version was 2.10.0-alpha4.

com.taoensso/nippy 2.10.0-alpha5 released

---

project.clj

com.taoensso/nippy 2.10.0-beta1 has been released. Previous version was 2.10.0-alpha5.

com.taoensso/nippy 2.10.0-beta1 released

---

project.clj

com.taoensso/timbre 4.1.2 has been released. Previous version was 4.1.1.

com.taoensso/timbre 4.1.2 released

---

project.clj

com.taoensso/nippy 2.10.0-RC2 has been released. Previous version was 2.10.0-RC1.

com.taoensso/nippy 2.10.0-RC2 released

---

project.clj

com.taoensso/nippy 2.10.0-RC3 has been released. Previous version was 2.10.0-RC2.

com.taoensso/nippy 2.10.0-RC3 released

---

project.clj

com.taoensso/nippy 2.11.0-alpha1 has been released. Previous version was 2.11.0-private3.

com.taoensso/nippy 2.11.0-alpha1 released

---

project.clj

com.taoensso/timbre 4.1.4 has been released. Previous version was 4.1.2.

com.taoensso/timbre 4.1.4 released

---

project.clj

com.taoensso/nippy 2.11.0-alpha2 has been released. Previous version was 2.11.0-alpha1.

com.taoensso/nippy 2.11.0-alpha2 released

---

project.clj

com.taoensso/nippy 2.11.0-alpha3 has been released. Previous version was 2.11.0-alpha2.

com.taoensso/nippy 2.11.0-alpha3 released

---

project.clj

com.taoensso/nippy 2.11.0-alpha5 has been released. Previous version was 2.11.0-alpha4.

com.taoensso/nippy 2.11.0-alpha5 released

---

project.clj

org.clojure/clojure 1.8.0-beta1 has been released. Previous version was 1.8.0-alpha5.

org.clojure/clojure 1.8.0-beta1 released

---

project.clj

aleph 0.4.1-beta1 has been released. Previous version was 0.4.1-alpha3.

aleph 0.4.1-beta1 released

---

project.clj

prismatic/schema 1.0.2 has been released. Previous version was 1.0.1.

prismatic/schema 1.0.2 released

---

project.clj

org.clojure/core.typed 0.3.12 has been released. Previous version was 0.3.11.

org.clojure/core.typed 0.3.12 released

---

project.clj

org.clojure/core.typed 0.3.14 has been released. Previous version was 0.3.12.

org.clojure/core.typed 0.3.14 released

---

project.clj

org.clojure/clojure 1.8.0-beta2 has been released. Previous version was 1.8.0-beta1.

org.clojure/clojure 1.8.0-beta2 released

---

project.clj

org.clojure/core.async 0.2.371 has been released. Previous version was 0.1.346.0-17112a-alpha.

org.clojure/core.async 0.2.371 released

---

project.clj

prismatic/schema 1.0.3 has been released. Previous version was 1.0.2.

prismatic/schema 1.0.3 released

---

project.clj

lein-ancient 0.6.8 has been released. Previous version was 0.6.7.

lein-ancient 0.6.8 released

---

project.clj

org.clojure/core.typed 0.3.15 has been released. Previous version was 0.3.14.

org.clojure/core.typed 0.3.15 released

---

project.clj

ring-middleware-format 0.7.0 has been released. Previous version was 0.6.0.

ring-middleware-format 0.7.0 released

---

project.clj

aleph 0.4.1-beta2 has been released. Previous version was 0.4.1-beta1.

aleph 0.4.1-beta2 released

---

project.clj

org.clojure/core.typed 0.3.16 has been released. Previous version was 0.3.15.

org.clojure/core.typed 0.3.16 released

---

project.clj

org.clojure/core.typed 0.3.17 has been released. Previous version was 0.3.16.

org.clojure/core.typed 0.3.17 released

---

project.clj

org.clojure/clojure 1.8.0-RC1 has been released. Previous version was 1.8.0-beta2.

org.clojure/clojure 1.8.0-RC1 released

---

project.clj

org.clojure/core.async 0.2.374 has been released. Previous version was 0.2.371.

org.clojure/core.async 0.2.374 released

---

project.clj

org.clojure/core.typed 0.3.18 has been released. Previous version was 0.3.17.

org.clojure/core.typed 0.3.18 released

---

project.clj

org.clojure/test.check 0.9.0 has been released. Previous version was 0.8.2.

org.clojure/test.check 0.9.0 released

---

project.clj

jonase/eastwood 0.2.2 has been released. Previous version was 0.2.1.

jonase/eastwood 0.2.2 released

---

project.clj

org.clojure/clojure 1.8.0-RC2 has been released. Previous version was 1.8.0-RC1.

org.clojure/clojure 1.8.0-RC2 released

---

project.clj

aleph 0.4.1-beta3 has been released. Previous version was 0.4.1-beta2.

aleph 0.4.1-beta3 released

---

project.clj

org.clojure/core.typed 0.3.19 has been released. Previous version was 0.3.18.

org.clojure/core.typed 0.3.19 released

---

project.clj

com.taoensso/nippy 2.11.0-alpha6 has been released. Previous version was 2.11.0-alpha5.

com.taoensso/nippy 2.11.0-alpha6 released

---

project.clj

org.clojure/clojure 1.8.0-RC3 has been released. Previous version was 1.8.0-RC2.

org.clojure/clojure 1.8.0-RC3 released

---

project.clj

prismatic/schema 1.0.4 has been released. Previous version was 1.0.3.

prismatic/schema 1.0.4 released
